In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/ratings-preproc/data_train.csv
/kaggle/input/ratings-preproc/data_test.csv


In [2]:
import pandas as pd

df_test = pd.read_csv('/kaggle/input/ratings-preproc/data_test.csv')
df_train = pd.read_csv('/kaggle/input/ratings-preproc/data_train.csv')

In [3]:
print(len(df_test))
df_test.head()

10000


,uid,mid,rating
0,598,502,4.5
1,471,6950,3.0
2,20,2235,3.0
3,528,7147,3.0
4,623,216,4.0


In [4]:
print(len(df_train))
df_train.head()

90004


,uid,mid,rating
0,462,214,4.0
1,638,2275,3.0
2,310,2452,3.5
3,319,1654,4.0
4,119,270,3.5


loading to nmpy arrays

In [5]:
uid_train = df_train["uid"].to_numpy()
print(uid_train)
mid_train = df_train["mid"].to_numpy()
print(mid_train)


[462 638 310 ... 265  43 467]
[ 214 2275 2452 ...   64  453 2526]


In [6]:
uid_test = df_test["uid"].to_numpy()
print(uid_test)
mid_test = df_test["mid"].to_numpy()
print(mid_test)

[598 471  20 ... 212 344 212]
[ 502 6950 2235 ... 4181  278 5420]


# UA and IA (step 1)

In [8]:
df_train = df_train.loc[(df_train!=0).any(axis=1)] #did nothing, wanted to eliminate all 0 ratings- non existent ratings

In [9]:
!pip install scikit-learn==0.24

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 50.6 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  error: subprocess-exited-with-error
  
  × Building wheel for scikit-learn (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (scikit-learn)


In [9]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [11]:
import pandas as pd
import numpy as np
from sklearn.metrics import root_mean_squared_error

# train and test dataframes assumed to have columns: userId, movieId, rating

# === 1. Compute user averages ===
user_mean = df_train.groupby("uid")["rating"].mean()

# === 2. Compute movie averages ===
movie_mean = df_train.groupby("mid")["rating"].mean()

# === 3. Global mean (backup if user/movie not in train set)
global_mean = df_train["rating"].mean()

# ---------------------------------------------
# User Average Predictions
# ---------------------------------------------
ua_pred = df_test["uid"].map(user_mean)    # maps user to mean rating
ua_pred = ua_pred.fillna(global_mean)      # in case user not in train

# RMSE UA
rmse_ua = root_mean_squared_error(df_test["rating"], ua_pred)


# ---------------------------------------------
# Item Average Predictions
# ---------------------------------------------
ia_pred = df_test["mid"].map(movie_mean)  # maps movie to mean rating
ia_pred = ia_pred.fillna(global_mean)      # in case movie not in train

# RMSE IA
rmse_ia = root_mean_squared_error(df_test["rating"], ia_pred)


print("RMSE User Average:", rmse_ua)
print("RMSE Item Average:", rmse_ia)


ImportError: cannot import name 'root_mean_squared_error' from 'sklearn.metrics' (/usr/local/lib/python3.11/dist-packages/sklearn/metrics/__init__.py)

In [ ]:
print(len(df_train))

In [ ]:
df_test = df_test.loc[(df_test!=0).any(axis=1)]

In [ ]:
print(len(df_test))

# SVD (step 2)

# UCF (step 4)

# evalutaion algorithm comparissons (step 5)